name: Generate Space Invaders

on:
  schedule:
    - cron: "0 */12 * * *"   # runs twice a day
  workflow_dispatch:          # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Space Invaders
        uses: Platane/snk@v3
        with:
          github_user_name: k-u-s-h-a-g-r-a-k-e-d-i-a
          outputs: |
            dist/space-invader.svg
            dist/space-invader-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
